Basic information search page
bernardro/actor-youtube-scraper pull request #60
Opened 2022-04-18 20:56 UTC by levent91

Added simplified results for keywords search.

@zpelechova let's test a bit.

2022-04-19 07:44 UTC, petrpatek requested changes
Great job! I have just a two small nitpicks.

2022-04-19 07:44 UTC, petrpatek commented on src/crawler_utils.js
> +const getBasicInformation = async (page, maxRequested, isSearchResultPage, input, requestUrl) => {
Five parameters are quite a lot, and the order can be easily mixed up. I would either wrap the parameters in some context object so the order does not matter or refactor it into multiple more straightforward functions.

2022-04-19 07:44 UTC, petrpatek commented on src/crawler_utils.js
> +                        await sleep(CONSTS.DELAY.HUMAN_PAUSE.max);
It feels a bit weird that the last property is not uppercase.

2022-04-19 13:14 UTC, metalwarrior665 requested changes

2022-04-20 22:29 UTC, levent91 commented on src/crawler_utils.js
> +        try {
tried to clean it up a bit, still not satisfied but looks better. Also added "/user/videos" type of channel format too, so let's try this one instead.

2022-04-21 07:33 UTC, metalwarrior665 commented on src/crawler_utils.js
> +        try {
Looks definitely better

2022-04-21 07:33 UTC, metalwarrior665 commented
@levent91 Ready to merge now?

2022-04-21 08:18 UTC, levent91 commented
Yes, we can test now

2022-04-21 10:57 UTC, merged